language: java

jdk: openjdk8

env:
  - DOCKER_IMAGEM=s1dn3y/alura-forun

addons:
  sonarcloud:
    organization: teste-alura
    token:
      secure: "R5xWteJluIKeRG/k+1SN3JFuK5GDgQTn+nwOHS5BJqNCytpJu9ETXyeV0jfMy27SQkkNKI5nWyZrW/IXdByTWXcGzHu1WOpmlYj6xGe/ucEYexlL1BlaZmD7FNnGI3HxXv5cqlLhhgflr+azdHzI5IHyNHrzDY1wVc54BZdQfZv84Vg7iDrhx/uUdGgcrLmcEdS/mOfqDdP2p6PRgfCyswpIOu47Fi8qM9OaVx4fBxcq/4jrHj7V5jrTe3AINEncfoGQsTu8OxVE9qw+KopmlbGcjBfZZoUDaehGQ41gK70xXppP2nEjS/kE01Igx17JI9ZrCd26xxAJqDNXafMKolVYtSDW/IwaaePH9PHO5pFrByVx8Q01LXbKhO6JfINwcwsu6uAV/PzuZYIcHQ1s/mZrOSmMQrZgG6ZHL2cBENKMiXqflcb7B4BRYLdvAkChpwNJ+ohy3OuBqxZsdzFB8q+j5pKAI3Gi2ukVYrdNDBGO+layrSm1etr0kpgcQecsmFLlGkpCYBcpnomLGX4vuX191lfC+D/G+A9LwrB0lEHSicJQDt2O791db5He2tvrn+NbPjjgQQTZ/F0jBjR21Dgc7q1LV6ftlVEGfoRILslDLOL0a1C/gsA3R5mfrSGXJJa2OviJO9zvTpGcMtfukYZ4CwgPdF6yaSYeG7IoF1M="

services:
  - docker

script:
  - mvn clean verify jacoco:report coveralls:report sonar:sonar -Dsonar.projectKey=teste-alura_forun

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: script
  script: bash docker_push

  email:
    if: branch = master
    recipients:
      - sm-alura-forum@alura.com.br
      - po-alura-forum@alura.com.br
    on_success: change
    on_failure: always
