language: java
sudo: false
jdk: openjdk8

env:
  - DOCKER_IMAGEM=s1dn3y/alura-forun

addons:
  sonarcloud:
    organization: teste-alura
    token:
      secure: "pO8r9Q2tJJwKk5FEHwRdnhuJBILEEA/0cB2TmznwMJ2NLLjZD/0Fn2ega5r3WQ48a1JS4TEwoUuD0Cxp7+8B8h7vjgfbGkAW7XDc5QZeA8A0q9gWeocj/wBqW+5bzTScIVtJQ+7sdRQ0mZ7kilmD2ZtVnZdDChOUyagBBRq0EQZx/sbj/Zss9BR3OjNtIZbcNQ58alHmHbkssckbnWbkNLyiQKgWYE9YeYJ6VV1VoZFZYBNHeUQgOWiG5vPYyk3/mLlSpeWCQhNbnGP+KwnlYBQiuU6yffxDtExzeQ6TrjAG5OFTCTck3bV+nqY8QmylnU/YUSz+cIcL5BX7o1fc43TdacHE2KKtOUMgCZi1CZqvp8rIqmHwNvSaMDZbmFCpoVHd+QxSHqFWMbKf0kYYJ3ikoWpHoTlDjRmu4TQUh5s/HHRZW5JB3XDQAfXqJqoZlA8LL8SrjhMc12U7+VMwd2CS3KO0rjHmJz/FzsOinph3iuT1QQlodEFlYR8Mwc3zKY8CzrPc/ncZXC3xmth4ykXk/GJ/cclqwEqlvlhJQQPCNaS4zNIkV8TDk3OHwzsdb4oOL3WU3ta7m+i+Xo2z5KzDGsxjFT6KRYAEfXa3ePh1Tme3dIcqGJgQUSXVXkjDbOGaY1keDxBlPHdR5to6F9vZdbkofBQaoZsvwC6WlX4="

services:
  - docker

script:
  - mvn clean verify jacoco:report coveralls:report sonar:sonar

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker-push.sh
  on:
    all_branches: true # necessário pq o travis trata tags como branches

notifications:
  slack:
    rooms:
      secure: IqRxqopasPRep4bbwiuDV/hTSjZB5idOtt84Tf1zjKGmVRR0kBUYEUDOKez7dbsOzTAntbCPXkFU+VdnXO5U+/OdLM7qJSlnBzGgkjvwFqa+EVLILA+0VhqLPK7WuN4CbhSZF7H1KRV5HsxBO9NhDpDbypVFaY8F4AgV4VDywN2w12oj1AMUs/SIctQktq5bj5cuQz+5jlDoFpCMRXYMg7ftIzN7vPoGAVNMjLSbJWgmcXTHf2yfYkOcSKdh3ZpUP3Ox3fYijnqk+bFou07WSZL1MWCPgy7T60FwyWM8IVyb2OjI8ndyAlsmE1gEEPyOJXHZaJmkkMp83EndJ4v0bfgiGTkFLaMPF9TlX+DgRtXkD5n9HM9uL740SYa6VrxZToLSzU7kaasoCBRSheVLmrDOijoisuW9iVAtqKwhGNtIlbbO9d9DC+zoYP1l4RyCzDCXOir4cun8a85lRmLhs7NT0C+uj7aEnhlIGs2G5uYxKTtWmpui+wC838DRPkuTt8ks3ol1c/qdx01Sd5nziUI4ExfKBNd/U68my8nyPkuhTAKZZNuIL/EjW/ajLEwzactoo/grgolcA7mmdv1l7Js0dFypPhd02nr5Mj/E1OThHbszOlAbA06Zmfa2d/s35oLc6zXMGxNrommiLTsnmuiAazmHdQPityBb8Lanwlo=
    on_success: always

#notifications:
#  email:
#    if: branch = develop
#    recipients:
#      - devs@servidor.com.br
#    on_success: never
#    on_failure: always
#
#  email:
#    if: branch = release
#    recipients:
#      - devs@servidor.com.br
#      - sm@servidor.com.br
#      - qa@servidor.com.br
#    on_success: change
#    on_failure: always
#
#  email:
#    if: branch = master
#    recipients:
#      - sm@servidor.com.br
#      - po@servidor.com.br
#    on_success: change
#    on_failure: always
