#!/bin/bash
DOCKER_IMAGEM=s1dn3y/alura-forun
DOCKER_TAG=latest
echo Passo 1...
docker build -t "$DOCKER_IMAGEM" .
echo Passo 2...
docker tag "$DOCKER_IMAGEM" "$DOCKER_TAG"
echo Passo 3...
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo Passo 4...
docker push "$DOCKER_TAG"